version: '3.8'
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
    ports:
      - "2000:27017"
    networks:
      - javarest
  read:
    build:
      context: ./Read
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - mongo
    depends_on:
      - mongo
      - eureka
    environment:
        - "MONGO=mongodb://mongo"
    networks:
      - javarest
  create:
    build:
      context: ./Create
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "4001:4001"
    links:
      - mongo
    depends_on:
      - mongo
      - eureka
    environment:
        - "MONGO=mongodb://mongo"
    networks:
      - javarest
  update:
    build:
      context: ./Update
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
      - "7001:7001"
    links:
      - mongo
    depends_on:
      - mongo
      - eureka
    environment:
        - "MONGO=mongodb://mongo"
    networks:
      - javarest
  delete:
    build:
      context: ./Delete
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    links:
      - mongo
    depends_on:
      - mongo
      - eureka
    environment:
        - "MONGO=mongodb://mongo"
    networks:
      - javarest
  conversion:
    build:
      context: ./Conversion
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001"
    links:
      - create
    depends_on:
      - mongo
      - eureka
    environment:
        - "CREATE=https://create/api/conversion/create"
    networks:
      - javarest
  eureka:
    build:
      context: ./Eureka
      dockerfile: Dockerfile
    networks:
      - javarest
  zuul:
    build:
      context: ./Zuul
      dockerfile: Dockerfile
    networks:
      - javarest
    depends_on:
      - eureka
networks:
  javarest: